---
- name: Ubuntu 16 support
  hosts: ipa
  user: ubuntu
  gather_facts: false
  environment: "{{ proxy_env }}"
  pre_tasks:
  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || ( export http_proxy={{proxy_env.http_proxy}};apt -qqy update && apt install -qqy python-minimal python2.7)"
    register: output
    changed_when:
    - output.stdout != ""
    - output.stdout != "\r\n"
  - name: Gathering Facts
    setup:

  tasks:
  - name: Create a new file for APT config
    file: path=/etc/apt/apt.conf.d/10disable-auto-apt  state=touch

  - name: Disable Automatic APT
    lineinfile:
      dest: /etc/apt/apt.conf.d/10disable-auto-apt
      line: 'APT::Periodic::Enable "0";'
      state: present

  - name: Add proxy settings
    lineinfile:
      path: /etc/environment
      regexp: '^http_proxy='
      line: 'http_proxy={{ proxy_env.http_proxy }}'
    when: proxy_env and proxy_env.http_proxy

  - name: Add proxy settings
    lineinfile:
      path: /etc/environment
      regexp: '^https_proxy='
      line: 'https_proxy={{ proxy_env.https_proxy }}'
    when: proxy_env and proxy_env.https_proxy

  - name: Install required packages
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
      - python-pip
      - qemu-utils

  - name: Install PIP virtualenv
    pip:
      name: virtualenv

  - name: Install diskimage-builder
    pip:
      name: diskimage-builder
      virtualenv: ~/dib
    become_user: ubuntu
