---
- name: Install base python
  hosts: ipa
  user: ubuntu
  gather_facts: false
  environment:
    "{{ proxy_env }}"

  vars:
    jenkins_build_number: "{{ lookup('env','BUILD_NUMBER') | default(default_jenkins_build_number, True) }}"
    dib_debug: "{{ lookup('env','DIB_DEBUG') | default(default_dib_debug, True) }}"
    ipa_strategy: "{{ lookup('env', 'IPA_STRATEGY') | default(default_ipa_strategy, True) }}"
    ubuntu_release: "{{ lookup('env','DIB_RELEASE') | default(default_ubuntu_release, True) }}"
    dib_include_elements: "ubuntu ironic-python-agent-ramdisk proliant-tools ilo baremetal devuser ipa-extra-hardware raid-tools clean-tasks"
    ca_bundle: "{{ lookup('env','CA_BUNDLE') | default(default_ca_bundle, True) }}"
    dib_environment:
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
      DIB_DEV_USER_SHELL: /bin/bash
      DIB_DEV_USER_USERNAME: devuser
      DIB_DEV_USER_PASSWORD: devuser
      DIB_DEV_USER_PWDLESS_SUDO: yes
      DIB_REPOREF_ironic_python_agent: origin/stable/stein
      DIB_RELEASE: "{{ ubuntu_release }}"
      DIB_DEBUG_TRACE: "{{ dib_debug }}"
      ELEMENTS_PATH: "/home/ubuntu/dib/extra/elements:/home/ubuntu/dib/share/ironic-python-agent-builder/dib"
  pre_tasks:
  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || ( export http_proxy={{ proxy_env.http_proxy }};apt -qqy update && apt install -qqy python-minimal python2.7)"
    register: output
    changed_when:
    - output.stdout != ""
    - output.stdout != "\r\n"
  - name: Gathering Facts
    setup:

  tasks:
  - name: Create a new file for APT config
    file: path=/etc/apt/apt.conf.d/10disable-auto-apt  state=touch

  - name: Disable Automatic APT
    lineinfile:
      dest: /etc/apt/apt.conf.d/10disable-auto-apt
      line: 'APT::Periodic::Enable "0";'
      state: present

  - name: Add proxy settings
    lineinfile:
      path: /etc/environment
      regexp: '^http_proxy='
      line: 'http_proxy={{ proxy_env.http_proxy }}'
    when: proxy_env and proxy_env.http_proxy

  - name: Add proxy settings
    lineinfile:
      path: /etc/environment
      regexp: '^https_proxy='
      line: 'https_proxy={{ proxy_env.https_proxy }}'
    when: proxy_env and proxy_env.https_proxy

  - name: Copy CA bundle
    copy:
      src: "{{ ca_bundle }}"
      dest: "/usr/local/share/ca-certificates/ca-bundle.crt"
    register: cabundle
    when: ca_bundle is defined
    environment: "{{ dib_environment }}"

  - name: Update certificates
    command: update-ca-certificates
    when: cabundle.changed

  - name: Install required packages
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
      - python-pip
      - qemu-utils

  - name: Install PIP virtualenv
    pip:
      name: virtualenv

  - name: Create venv
    shell: |
       virtualenv dib
    become_user: ubuntu
    args:
      creates: ~/dib

  - name: Copy extra elements
    synchronize:
      src: files/extra
      dest: ~/dib/
#  - name: Clone DIB
#    git:
#      repo: "https://git.openstack.org/openstack/diskimage-builder"
#      dest: ~/dib/diskimage-builder
#    become_user: ubuntu

#  - name: Run PIP
#    shell: |
#      source bin/activate
#      cd ~/dib/diskimage-builder
#      pip install -e .
#    args:
#      chdir: ~/dib
#    become_user: ubuntu

  - name: Install diskimage-builder
    pip:
      name: diskimage-builder
      virtualenv: ~/dib
    become_user: ubuntu

  - name: Install diskimage-builder
    pip:
      name: ironic-python-agent-builder
      virtualenv: ~/dib
    become_user: ubuntu

  - name: Remove dhcp-all-interfaces from deps
    lineinfile:
      dest: ~/dib/share/ironic-python-agent-builder/dib/ironic-python-agent-ramdisk/element-deps
      state: absent
      regexp: '^dhcp-all-interfaces$'
    become_user: ubuntu
    when: ipa_strategy == "static"

  - name: Create image
    shell: |
      source ~/dib/bin/activate
      disk-image-create -a amd64 -o ubuntu-amd64-{{ ubuntu_release }}.qcow2 --logfile build.log {{ dib_include_elements }}
      # {% if ipa_strategy == 'dhcp' %}dhcp-all-interfaces{% endif %}
    environment: "{{ dib_environment }}"
    args:
      chdir: ~/
      executable: /bin/bash
    become_user: ubuntu


  - name: Fetch images ramdisk
    synchronize:
      src: ubuntu-amd64-{{ ubuntu_release }}.initramfs
      dest: "/data/ipa_images/{{ jenkins_build_number }}_ubuntu-amd64-{{ ubuntu_release }}.initramfs"
      mode: pull

  - name: Fetch images kernel
    synchronize:
      src: ubuntu-amd64-{{ ubuntu_release }}.kernel
      dest: "/data/ipa_images/{{ jenkins_build_number }}_ubuntu-amd64-{{ ubuntu_release }}.kernel"
      mode: pull

  - name: Fetch build.log
    synchronize:
      src: build.log
      dest: "{{ jenkins_build_number }}_build.log"
      mode: pull
    tags:
      - fetch-logs

- name: Copy images to webserver path
  hosts: hypervisor
  gather_facts: false
  vars:
    jenkins_build_number: "{{ lookup('env','BUILD_NUMBER') | default(default_jenkins_build_number, True) }}"
    ubuntu_release: "{{ lookup('env','DIB_RELEASE') | default(default_ubuntu_release, True) }}"
  tasks:

  - name: Change file permissions
    file:
      path: "/data/ipa_images/{{ jenkins_build_number }}_ubuntu-amd64-{{ ubuntu_release }}.kernel"
      mode: 0644

  - name: Get sha256 for ramdisk
    stat:
      checksum_algorithm: sha256
      path: "/data/ipa_images/{{ jenkins_build_number }}_ubuntu-amd64-{{ ubuntu_release }}.initramfs"
    register: ramdisk_sha

  - name: Get sha256 for kernel
    stat:
      checksum_algorithm: sha256
      path: "/data/ipa_images/{{ jenkins_build_number }}_ubuntu-amd64-{{ ubuntu_release }}.kernel"
    register: kernel_sha

  - name: Copy sha256 file for ramdisk
    copy:
      content: "{{ramdisk_sha.stat.checksum}} ubuntu_ramdisk"
      dest: /var/www/html/ubuntu_ramdisk.sha256

  - name: Copy sha256 file for kernel
    copy:
      content: "{{kernel_sha.stat.checksum}} ubuntu_kernel"
      dest: /var/www/html/ubuntu_kernel.sha256

  - name: Copy ramdisk image to web server path
    synchronize:
      src:  "/data/ipa_images/{{ jenkins_build_number }}_ubuntu-amd64-{{ ubuntu_release }}.initramfs"
      dest: /var/www/html/ubuntu_ramdisk

  - name: Copy kernel image to web server path
    synchronize:
      src:  "/data/ipa_images/{{ jenkins_build_number }}_ubuntu-amd64-{{ ubuntu_release }}.kernel"
      dest: /var/www/html/ubuntu_kernel
