#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

SCRIPTDIR=$(dirname $0)
IPADIR=/tmp/ironic-python-agent
VENVDIR=/opt/ironic-python-agent

PACKAGE=${DIB_IPA_HARDWARE_PACKAGE:-hardware${DIB_IPA_HARDWARE_VERSION:+==}${DIB_IPA_HARDWARE_VERSION:-}}

# Generate upper-constraints
$IPADIR/imagebuild/common/generate_upper_constraints.sh $IPADIR/upper-constraints.txt

# Install the python hardware package inside the virtual environment.
$VENVDIR/bin/pip install -c $IPADIR/upper-constraints.txt $PACKAGE

# Because the ironic-python-agent systemd unit does not activate the virtualenv
# before executing the ironic-python-agent script, the PATH is not updated to
# point to the bin directory in the virtual environment. We add this symlink so
# that ironic-python-agent sees the hardware-detect tool in its PATH.
ln -s $VENVDIR/bin/hardware-detect /usr/local/bin/hardware-detect

# Install additional packages as requested.
if [[ -n ${DIB_IPA_EXTRA_HARDWARE_PACKAGES:-} ]]; then
    install-packages ${DIB_IPA_EXTRA_HARDWARE_PACKAGES}
fi
