#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail


if [[ $DISTRO_NAME = &quot;ubuntu&quot; || $DISTRO_NAME = &quot;debian&quot; ]]; then
 update-ca-certificates
fi
