#!/bin/bash

echo "Remove /etc/resolv.conf"
rm /etc/resolv.conf
test -f /etc/resolv.conf.ORIG && rm /etc/resolv.conf.ORIG
echo "Create soft link /run/systemd/resolve/stub-resolv.conf"
ln -s /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf


# remove /lib/systemd/network/99-default.link to be able to get member mac address
# it othwrwise gets configured with random mac
rm /lib/systemd/network/99-default.link

# Disable time sync
systemctl disable  systemd-timesyncd.service

# enable ssh password
sed -i 's|PasswordAuthentication no|PasswordAuthentication yes|g' /etc/ssh/sshd_config
# Disable exec on usr/lib/systemd/system/ironic-python-agent.service
chmod -x /usr/lib/systemd/system/ironic-python-agent.service

echo "Add udev rules service"
mkdir /etc/systemd/system/systemd-udevd.service.d
cat > /etc/systemd/system/systemd-udevd.service.d/10-bootif.conf  <<EOF
[Service]
ExecStartPre=-/bin/udev-bootif.sh
EOF

echo "Add udev script exe permissions"

chmod +x /bin/udev-bootif.sh

cat > /etc/netplan/bond.yaml << EOF
network:
    version: 2
    renderer: networkd
    ethernets:
        port1:
            dhcp4: false
            dhcp6: false
            match:
                name: enoboot0
        port2:
            dhcp4: false
            dhcp6: false
            match:
                name: enoboot1
    bonds:
        bond0:
            dhcp4: yes
            interfaces:
            - port1
            - port2
            parameters:
                mode: 802.3ad
                mii-monitor-interval: 100
EOF

cat > /etc/modprobe.d/systemd.conf << EOF
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.
#
# When bonding module is loaded, it creates bond0 by default due to max_bonds
# option default value 1. This interferes with the network configuration
# management / networkd, as it is not possible to detect whether this bond0 was
# intentionally configured by the user, or should be managed by
# networkd/NM/etc. Therefore disable bond0 creation.

options bonding max_bonds=0
EOF

cat > /etc/modprobe.d/bonding.conf << EOF
alias bond0 bonding
options bonding mode=4 lacp_rate=1 xmit_hash_policy=2 miimon=100 downdelay=200 updelay=200 max_bonds=0
EOF
