#!/bin/bash

echo "Create ipa-rescue-config directory and file"
mkdir /etc/ipa-rescue-config
touch /etc/ipa-rescue-config/ipa-rescue-password

echo "Disable ureadahead"
systemctl disable ureadahead.service

echo "Adding message to /etc/issue"
cat > /etc/issue <<EOF
 ██████╗ ██████╗ ███████╗███╗   ██╗███████╗████████╗ █████╗  ██████╗██╗  ██╗
██╔═══██╗██╔══██╗██╔════╝████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██╔════╝██║ ██╔╝
██║   ██║██████╔╝█████╗  ██╔██╗ ██║███████╗   ██║   ███████║██║     █████╔╝
██║   ██║██╔═══╝ ██╔══╝  ██║╚██╗██║╚════██║   ██║   ██╔══██║██║     ██╔═██╗
╚██████╔╝██║     ███████╗██║ ╚████║███████║   ██║   ██║  ██║╚██████╗██║  ██╗
 ╚═════╝ ╚═╝     ╚══════╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝

██╗██████╗  ██████╗ ███╗   ██╗██╗ ██████╗
██║██╔══██╗██╔═══██╗████╗  ██║██║██╔════╝
██║██████╔╝██║   ██║██╔██╗ ██║██║██║
██║██╔══██╗██║   ██║██║╚██╗██║██║██║
██║██║  ██║╚██████╔╝██║ ╚████║██║╚██████╗
╚═╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝ ╚═════╝
EOF

# Allow password login for rescue user
sed -i 's|PasswordAuthentication no|PasswordAuthentication yes|g' /etc/ssh/sshd_config

# remove snapd
apt -y --purge remove snapd liblxc-common liblxc1 lxcfs lxd-client
apt -y clean
apt -y autoremove

# disable mdadm auto assembly
echo "AUTO -all" >> /etc/mdadm/mdadm.conf
