#!/bin/bash

# Delay start because of LACP bonding
echo "Add delay service start for IPA"
mkdir -p /etc/systemd/system/ironic-python-agent.service.d
cat > /etc/systemd/system/ironic-python-agent.service.d/delay.conf <<EOF
[Service]
ExecStartPre=/bin/sleep 45
EOF

echo "Add udev rules service"
mkdir /etc/systemd/system/systemd-udevd.service.d
cat > /etc/systemd/system/systemd-udevd.service.d/10-bootif.conf  <<EOF
[Service]
ExecStartPre=-/bin/udev-bootif.sh
EOF

echo "bonding" >> /etc/modules

cat > /etc/network/interfaces <<EOF
auto enoboot0
iface enoboot0 inet manual
    bond-master bond0
    mtu 1500

auto enoboot1
iface enoboot1 inet manual
    pre-up sleep 5
    bond-master bond0
    mtu 1500

auto bond0
iface bond0 inet dhcp
    bond-mode 4
    bond_xmit_hash_policy layer3+4
    bond-lacp-rate 1
    bond-miimon 100
    bond-slaves none
    mtu 1500
EOF

# disable systemd-networkd
systemctl disable systemd-networkd.socket systemd-networkd networkd-dispatcher systemd-networkd-wait-online
apt -y purge netplan.io
systemctl disable systemd-resolved.service
rm /etc/resolv.conf
touch /etc/resolv.conf
# make sure dhcp client can update resolv.conf
rm /etc/dhcp/dhclient-enter-hooks.d/resolved
